### ISSUE TITLE
Requirements conversion handling intervals

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#35]
Using indigodc-2-a4c.py with the custom_types.yaml converts
```

 tosca.nodes.indigo.Container.Runtime.Docker:
    derived_from: tosca.nodes.SoftwareComponent
    capabilities:
      host:
        type: tosca.capabilities.indigo.Container.Docker
      scalable:
        type: tosca.capabilities.Scalable
  requirements:
    - host:
        capability: tosca.capabilities.Container
        node: tosca.nodes.Compute
        relationship: tosca.relationships.HostedOn
occurrences: [0, 1]
```
to

```
  tosca.nodes.indigo.Container.Runtime.Docker:
    derived_from: tosca.nodes.SoftwareComponent
    capabilities:
      host:
        type: tosca.capabilities.indigo.Container.Docker
      scalable:
        type: tosca.capabilities.Scalable
  requirements:
  - host:
      capability: tosca.capabilities.Container
      node: tosca.nodes.Compute
      relationship: tosca.relationships.HostedOn
      occurrences:
      - 0
      - 1
```

_occurrences:_ should be [0,1]
