### ISSUE TITLE
[A4C] CSARs should contain the import path in their version

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#53]
Instead of having a version for the CSARs containing the normative types, we should store the path that is used by the topologies that make use of that CSAR. 
instead of:
```
metadata:
  template_name: tosca-normative-types
  template_author: TOSCA TC
  template_version: 1.0.0-ALIEN20
```

we should have 
```
metadata:
  template_name: tosca-normative-types
  template_author: TOSCA TC
  template_version: https://raw.githubusercontent.com/alien4cloud/tosca-normative-types/master/normative-types.yml
```
