### ISSUE TITLE
[A4C] Inputs default values are not rendered correctly

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#63]
```
    rclone_conf:
      type: string
      description: nextcloud link to access via webdav
      required: yes
      default: "/srv/mods/.rclone.conf"
```
is rendered as

```
    rclone_conf:
      type: string
      required: true
      default: 
              definition: false
              value: "/srv/mods/.rclone.conf"
```
