### ISSUE TITLE
[A4C] OpenStack Tosca standard error tosca.artifacts.Root

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#66]
When trying to import the types from OpenStack implementation at [https://github.com/openstack/tosca-parser/blob/master/toscaparser/elements/TOSCA_definition_1_0.yaml](https://github.com/openstack/tosca-parser/blob/master/toscaparser/elements/TOSCA_definition_1_0.yaml), A4C fails when parsing **tosca.artifacts.Root**. The **alien4cloud.tosca.parser.impl.base.TypeNodeParser** parser tries to instantiate a property wrapper **org.alien4cloud.tosca.model.definitions.PropertyDefinition** with a String value as a sole parameter (by searching for a constructor accepting a String value). Unfortunately that doesn't exist in the property wrapper, so it fails.

**Comment by asalic** [comment]
Example that fails:
```
artifact_types:
  tosca.artifacts.Root:
    description: >
      The TOSCA Artifact Type all other TOSCA Artifact Types derive from
    properties:
      version: version

tosca_definitions_version: "tosca_simple_yaml_1_0"
```
