### ISSUE TITLE
[A4C] Fails when not connected to the internet and can't verify file existance

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#68]
Alien4Cloud contains various validation algorithms. 
One of these deals with the links to files in the TOSCA definition of types.
The application will try to check the existence of the files included with any property, e.g.:

```
  tosca.nodes.indigo.CmsOneclient:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      oneclient_pkg:
        type: string
        required: true
    artifacts:
      oneclient_role:
        file: indigo-dc.oneclient
        type: tosca.artifacts.AnsibleGalaxy.role
    interfaces:
      Standard:
        configure:
          implementation: https://raw.githubusercontent.com/indigo-dc/tosca-types/oneclient/artifacts/onedata/cms_oneclient.yml
          inputs:
            oneclient_pkg:
              get_property:
              - SELF
              - oneclient_pkg
```

the existance of the file at **https://raw.githubusercontent.com/indigo-dc/tosca-types/oneclient/artifacts/onedata/cms_oneclient.yml**.
