### ISSUE TITLE
[A4C] Deserialize PropertyValues correctly

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#72]
The A4C TOSCA text editor uses Jackson to deserialize the topology. **alien4cloud.json.deserializer.PropertyValueDeserializer** doesn't handle all cases of **org.alien4cloud.tosca.model.definitions.PropertyValue<T>** like a **org.alien4cloud.tosca.model.definitions.ListPropertyValue**.

**Comment by asalic** [comment]
```
  node_templates:
    Docker:
      type: "tosca.nodes.indigo.Container.Runtime.Docker"
      capabilities:
        host:
          properties:
            publish_all: false
            publish_ports:
            - protocol: "tcp"
              source: 5000
```

is deserialized as

```
  node_templates:
    Docker:
      type: tosca.nodes.indigo.Container.Runtime.Docker
      capabilities:
        host:
          properties:
            publish_all: false
            publish_ports: 
              definition: false
              value: 
                - 
                  protocol: tcp
                  source: 5000
```
