### ISSUE TITLE
[A4C] Required property TOSCA function

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#75]
A4C fails to validate templates that have a required property set as a TOSCA function, although, the Orchestrator should set the property. For instance, in the following case:

```
    wn_node:
      type: tosca.nodes.indigo.LRMS.WorkerNode.Kubernetes
      properties:
        front_end_ip: { get_attribute: [ lrms_server, private_address, 0 ] }
      requirements:
        - host: lrms_wn

    lrms_server:
      type: tosca.nodes.indigo.Compute
      capabilities: .....................
```
it's impossible to set the value before hand, as the _private_address_ is to be decided during the deployment.
