### ISSUE TITLE
[A4C] interfaces configure implementation not rendered correctly text editor

### ISSUE THREAD

**Issue by asalic** [indigo-dc/alien4cloud-deep#77]
A4C renders the implementation as a JSON node (outputting the fields with their values) e.g. this

```
    deepaas_app:
      type: tosca.nodes.SoftwareComponent
      interfaces:
        Standard:
          configure: 
            implementation: https://raw.githubusercontent.com/indigo-dc/tosca-types/deepaas/artifacts/deepaas/deepaas.yml
```

is rendered as 

```
    deepaas_app:
      type: \"tosca.nodes.SoftwareComponent\"
      interfaces:
        tosca.interfaces.node.lifecycle.Standard:
          configure:
            implementation:
              file: \"https://raw.githubusercontent.com/indigo-dc/tosca-types/deepaas/artifacts/deepaas/deepaas.yml\"
              type: \"tosca.artifacts.Implementation.YAML\"
```
